configfile: "config/config.yaml"

rule all:
    input:
        "results/statistics/lmm.assoc.txt.gz",
        "results/figures/manhattan.png",
        "results/figures/qq.png",
        "results/figures/regional/.done",
        "results/finemapping/.done",
        "results/haplotype/causal_ld_heatmap.png",
        "results/haplotype/genotype_effect.png",

include: "rules/ref.smk"
include: "rules/processing.smk"
include: "rules/statistics.smk"
include: "rules/plotting.smk"
include: "rules/finemapping.smk"
include: "rules/haplotype.smk"
